default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password:

test:
  <<: *default
  database: shuffle_test_test

development:
  <<: *default
  database: shuffle_test_development

deployment: &deployment
  adapter: postgresql
  encoding: unicode
  pool: 10
  database: <%= ENV['OPENSHIFT_APPNAME']%>
  host: <%= ENV['$OPENSHIFT_POSTGRESQL_DB_HOST'] %>
  port: <%= ENV['$OPENSHIFT_POSTGRESQL_DB_PORT'] %>
  username: <%= ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME'] %>
  password: <%= ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD'] %>

staging:
  <<: *deployment

production:
  <<: *deployment
